lab_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myuser.urls')),
    path('Track/', include('track.urls')),
    path('Trainee/', include('trainee.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


myuser/urls.py
from django.urls import path
from .views import *
app_name = 'myuser'
urlpatterns = [
    path("Login/", Login, name='login'),
    path("Register/", Register, name='register'),
    path("Logout/", Logout, name='logout'),
]

track/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', alltracks, name="alltracks"),
    path('Insert/', Insert, name="inserttrack"),
    path('Update/<int:id>/', Update, name='updatetrack'),
    path('Delete/<int:id>/', Delete, name='deletetrack')
]

trainee/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Alltrainee, name='alltrainees'),
    path('Insert/', Insert, name="insert_tr"),
    path('Update/<int:id>/', Update, name='update_tr'),
    path('Delete/<int:id>/', Delete, name='delete_tr')
]

myuser/models.py
from django.db import models

# Create your models here.

track/models.py
from django.db import models
# Create your models here.

class Track(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=100, null=False, unique=True)

trainee/models.py
from django.db import models

# Create your models here.

class Trainee (models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, null=False)
    email = models.EmailField(max_length=100, unique=True, null=False)
    image = models.ImageField(upload_to='trainees/images/')

myuser/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def Login(request):
    return render(request, 'myuser/login.html')

def Register(request):
    return render(request, 'myuser/register.html')

def Logout(request):
    return HttpResponse("<h1> Goodbye </h1>")

track/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Track

# Create your views here.

def alltracks(request):
    context={}
    context['tracks'] = Track.objects.all()
    return render(request, 'track/list.html', context)

def Insert(request):
    if request.method == 'POST':
        name = request.POST['track']
        Track.objects.create(name=name)
    return render(request, 'track/insert.html')

def Update(request, id):
    return HttpResponse(f"<h1>Track {id} updated</h1>")

def Delete(request, id):
    return HttpResponse(f"<h1>Track {id} deleted</h1>")


trainee/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Trainee
# Create your views here.

def Alltrainee(request):
    context={}
    context['trainees'] = Trainee.objects.all()
    return render(request, 'trainee/list.html', context)

def Insert(request):
    if request.method == 'POST':
       name = request.POST['trName']
       email = request.POST['trEmail']
       image = request.FILES.get('trImage')
       Trainee.objects.create(name=name, email=email, image=image)
       
    return render(request, 'trainee/insert.html')

def Update(request, id):
    return HttpResponse(f"<h1>Trainee {id} updated</h1>")

def Delete(request, id):
    return HttpResponse(f"<h1>Trainee {id} deleted</h1>")


myuser/templates/myuser/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
{% load static %}

{%block style %}
<link href="{% static 'css/style.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Hello from Login</h1>

<a href="{% url 'myuser:logout'%}">Logout</a>

{% endblock %}

myuser/templates/myuser/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}
{% load static %}

{%block style %}
<link href="{% static 'css/register.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<form method="GET" action="..\templates\Thankyou.html">
    <table align="center">
        <tr>
            <th colspan="2">
                <h2>Registration Page</h2>
            </th>
        </tr>
        <tr>
            <td>
                <label for="fname" id="fname">First Name:</label>
            </td>
            <td>
                <input type="text" id="fname" name="fname" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="lname" id="lname">Last Name:</label>
            </td>
            <td>
                <input type="text" id="lname" name="lname" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="email" id="email">Email:</label>
            </td>
            <td>
                <input type="email" id="email" name="email" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="pass" id="pass">Password:</label>
            </td>
            <td>
                <input type="password" id="pass" name="pass" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="rpass" id="rpass">Repeat Password:</label>
            </td>
            <td>
                <input type="password" id="rpass" name="rpass" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="bdate" id="bdate">Birth Date:</label>
            </td>
            <td>
                <input type="date" id="bdate" name="bdate" required>
            </td>
        </tr>
        <tr>
            <td>
                <label for="pic" id="pic">User Picture:</label>
            </td>
            <td>
                <input type="file" id="pic" name="pic">
            </td>
        </tr>
        <tr>
            <td>
                <label for="gender" id="gender">Gender:</label>
            </td>
            <td>
                <input type="radio" name="gender" id="male">
                <label for="male">Male</label>
                <input type="radio" name="gender" id="female">
                <label for="female">Female</label><br>
            </td>
        </tr>
        <tr>
            <td>
                <label for="faculty" id="faculty">Faculty of:</label>
            </td>
            <td>
                <select name="faculty" id="faculty">
                    <option value="" disabled selected>-- select option --</option>
                    <option value="engineering">Engineering</option>
                    <option value="Medicine">Medicine</option>
                    <option value="Pharmacy">Pharmacy</option>
                    <option value="Dentistry">Dentistry</option>
                    <option value="Business">Business</option>
                </select>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;">
                <label for="interests" id="interests">Interests:</label>
            </td>
            <td>
                <input type="checkbox" name="interests" id="programming">
                <label for="programming">Programming</label><br>

                <input type="checkbox" name="interests" id="swimming">
                <label for="swimming">Swimming</label><br>

                <input type="checkbox" name="interests" id="reading">
                <label for="reading">Reading</label><br>

                <input type="checkbox" name="interests" id="football">
                <label for="football">Football</label><br>
            </td>
        </tr>
        <tr>
            <td>About you:</td>
            <td>
                <textarea name="about" id="about"></textarea>
            </td>
        </tr>
        <tr>
            <td>I agreed to terms and condition</td>
            <td>
                <input type="checkbox" name="terms" id="terms" required>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Register">
                <input type="reset" value="Reset">
                <a href="{% url 'myuser:login'%}" style="margin: 10px;">Login</a>
            </td>
        </tr>
    </table>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base-Parent{% endblock %}</title>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <script src="{% static 'js/asd.js'%}"></script>
</head>

<body>
    <table width="100%" id="base">
        <tr>
            <td id="header">
                <a href="{% url 'alltracks'%}">Tracks</a>
                <a href="{% url 'alltrainees'%}">Trainees</a>
            </td>
        </tr>
        <tr>
            <td>
                {% block content %}
                Content
                {% endblock %}
            </td>
        </tr>
        <tr id="footer">
            <td>
                Copyrights &#169; are reserved to ITI
            </td>
        </tr>
    </table>
</body>

</html>

track/templates/track/insert.html
{% extends 'base.html'%}

{% block title%}
    Insert Track
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="track">Track Name:</label>
    <input type="text" id="track" name="track">
    <input type="submit" id="Insert Track">
</form>
{% endblock %}

track/templates/track/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
tracks
{% endblock %}

{% block content %}
<a href="{% url 'inserttrack'%}">Insert Track</a>

<h1>All Tracks</h1>
<table width="100%" border="solid" style="border-collapse: collapse;">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Action</th>
  </tr>
  {% for track in tracks %}
  <tr>
    <td>{{ track.id }}</td>
    <td>{{ track.name }}</td>
    <td>
      <div class="action">
        <a href="{% url 'updatetrack' track.id %}">Update</a>
        <a href="{% url 'deletetrack' track.id %}">Delete</a>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

trainee/templates/trainee/insert.html
{% extends 'base.html'%}

{% block title%}
    Insert Trainee
{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="trName">Name:</label>
    <input type="text" id="trName" name="trName">
    <br><br>
    <label for="trEmail">Email:</label>
    <input type="email" id="trEmail" name="trEmail">
    <br><br>
    <label for="trImage">Image:</label>
    <input type="file" id="trImage" name="trImage">
    <br><br>
    <input type="submit" id="Insert Trainee">
</form>
{% endblock %}

trainee/templates/trainee/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Trainees
{% endblock %}

{% block content %}
<a href="{% url 'insert_tr' %}">New Trainee</a>
<h1>All Trainees</h1>
<table width="100%" border="1" style="border-collapse: collapse;">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Image</th>
    <th>Action</th>
  </tr>
  {% for trainee in trainees %}
  <tr>
    <td>{{ trainee.id }}</td>
    <td>{{ trainee.name }}</td>
    <td>
      <img src="{{ trainee.image.url }}" width="100px" height="100px">
    </td>
    <td>
      <div class="action">
        <a href="{% url 'update_tr' trainee.id %}">Update</a>
        <a href="{% url 'delete_tr' trainee.id %}">Delete</a>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>
{% endblock %}